# Site settings
title: Sameer R. Jadhav
logo: https://avatars2.githubusercontent.com/u/22472951
logo_custom: images/avatar2.png
description: Java Developer
show_downloads: true
google_analytics:

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"  #true, false, none
resume_name:                    "Sameer R. Jadhav"
resume_title:                   "Senior Technical Lead at PTC"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "sameer.jadhav01@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "9970089813"
resume_contact_address:         "Pune, India"

resume_header_contact_info:     "Pune, IN • 9970089813 • sameer.jadhav01@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>About 7 years 3 months + of Software Development experience in designing, developing and implementing full-featured Web Applications in various domains (Manufacturing Engineering Services, Telecom & PLM) using JAVA/Java EE. Have been a part of multiple successful software development lifecycles from inception to execution to delivery. Involved in requirement gathering, solution architecture, product development, performance optimizations, product consulting, integrations and extensive product customization's, worked with globally distributed agile teams to ensure high-quality timely deliverables. I see myself as a language and framework agnostic problem solver using Computer Science. Skilled in Java, J2EE, RESTful Web Services, Groovy, Spring, Hibernate, SQL, NoSQL, ZK, Angular, JavaScript, HTML. Strong engineering professional with a master's in Computer Engineering from the University of Pune.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_skills:          true
resume_section_experience:      true
resume_section_projects:        true
resume_section_education:       true
resume_section_recognition:     false
resume_section_associations:    false
resume_section_links:           false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_linkedin_url:          "https://www.linkedin.com/in/sameerravikantjadhav/"
  resume_github_url:            "https://github.com/JadhavSameer"
  resume_twitter_url:           "https://twitter.com/samjadhavweb"
  resume_website_url:           "https://jadhavsameer.github.io"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts

theme: jekyll-theme-minimal
